import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import {Box, Button, Grid, Typography} from "@mui/material";
import NinaNitzscheIcon from "../../ninanitzschephotography/public/NinaNitzscheIcon.png";
import { Link } from 'react-scroll';
import QuiltedImageList from "./QuiltedImageList";
import ContactForm from './contactForm';
import Appbar from "./Appbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nina Nitzsche Photography</title>
        <meta charSet="utf-8"/>
        <link rel="icon" href="%PUBLIC_URL%/favicon.ico"/>
        {/* eslint-disable-next-line @next/next/no-css-tags */}
        <link rel="stylesheet" href="%PUBLIC_URL%/index.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="theme-color" content="#000000"/>
        <meta
            name="description"
            content="Web site created using create-react-app"
        />
        <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png"/>
        <link rel="manifest" href="%PUBLIC_URL%/manifest.json"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Appbar/>
        <div className={styles.App}>
        <Box sx={{ display: 'flex' }} className={styles.box}>
          <div className={styles.heading}  >
            <Image
                src={NinaNitzscheIcon}
                alt="Picture of the author"
                width="200"
            />
            <p className={styles.largeImageLargeText}>Nina Nitzsche Photography</p>
            <h1 className={styles.largeImageSmallText}>Familienfotograf aus Johannisthal</h1>
          </div>
        </Box>

        <header className={styles.AppHeader}>
          <Grid container  spacing={2} className={`${styles.informationText} ${styles.informationTextCenter}  ${styles.aboutMe}`} id="AboutMe">
            <Grid item xs={12} sm={6} className={styles.about}>

            </Grid>
            <Grid item xs={12} sm={6}>
              <h2>
                Hi ihr Lieben,
                ich bin Nina!
              </h2>
              <p>
                Als zweifache Mama habe ich schnell gemerkt, wie wichtig es ist die kleinen Momente aufzufangen. Denn das sind genau die Momente, die viel zu schnell verblassen.


                Ich bin davon überzeugt, dass besonders bei der Arbeit mit Familien eine besondere Empathie gefragt ist und freue mich, wenn ich euch mit dieser Empathie begleiten darf wertvolle Familienfotos zu schaffen.


                Als Familienfotografin ist es mir wichtig, dass jeder von euch auf den Fotos zu sehen ist.
                Schiefe Zähne, krumme Nase, Brille - Das interessiert die Kinder null.
                Eure Kinder interessieren sich aber für euch und lieben euch so wie ihr seid. Also ab vor die Linse. Lasst uns eure Emotionen, Momente und Geschichten festhalten.
              </p>
              <Link
                  activeClass="active"
                  to="Kontakt"
                  spy={true}
                  smooth={true}
                  offset={-70}
                  duration={500}
              >
              <Button variant="outlined">KONTAKTIEREN</Button>
              </Link>
              </Grid>
          </Grid>
          <Grid container spacing={2} className={`${styles.informationText} ${styles.informationTextCenter}`}>
            <Grid item xs={12} md={4}>
              <h3 className={styles.h3}>Die Summe unseres Lebens sind die Stunden, in denen wir liebten.
                <p>- William
                  Busch</p></h3>
            </Grid>
            <Grid item  xs={12} md={4}>
              <p>
                {/* eslint-disable-next-line react/no-unescaped-entities */}
                Wisst ihr was ich liebe? Ich liebe meine Familie, "natürliches Outdoor-Licht" und glückliche Menschen noch glücklicher zu machen.

                Deshalb bin ich Familienfotografin in Johannisthal. Denn ich glaube, dass wir uns die Natur nicht nur das schönste Licht, sondern auch die schönste Individualität schenkt.
              </p>            </Grid>
            <Grid item  xs={12} md={4}>
              <p>
                Was mache ich als Familienfotografin?
                <ul>
                  <li><strong className={styles.strong}>Kinderfotos</strong>, die beim Spielen & Lachen entstehen</li>
                  <li><strong className={styles.strong}>Paarbilder</strong>, die euch so zeigen wie ihr seid</li>
                  <li><strong className={styles.strong}>Familienfotos</strong> - Völlig unverkrampft & mit viel Spaß</li>
                  <li><strong className={styles.strong}>Baby- & Babybauchbilder</strong></li>
                </ul>
              </p>
            </Grid>
          </Grid>
        </header>

        <Box sx={{ display: 'flex' }} className={styles.location}>
          <div className={styles.heading}  >
            <Image
                src={NinaNitzscheIcon}
                alt="Picture of the author"
                width="200"
            />
            <p className={styles.largeImageLargeText}>Newborn, Schwangerschaft, Paarfotografie</p>
            <h1 className={styles.largeImageSmallText}> Verzaubernde Familienbilder aus Berlin Treptow</h1>
          </div>
        </Box>
        <Grid container  spacing={2} className={`${styles.aboutMe}  ${styles.treptow} ${styles.NoPadding}`}>
          <Grid item xs={12} md={6} className={`${styles.automnBackground}  ${styles.splittetBackgroundSize}`}>
          </Grid>
          <Grid item xs={12} md={6} className={styles.basicPadding}>
            <h3 className={`${styles.schnorkel}  ${styles.darkFont}`} color="black">Warum ich in Treptows Bezirken Familienfotos mache...</h3>

            <p>

              Wusstet ihr, dass Berlin-Treptow jede Menge zu bieten hat? Wer an Treptow denkt, der denkt zu erst an die <strong className={styles.strong}>Wuhlheide (FEZ)</strong> und den <strong className={styles.strong}>Treptower Park</strong>.
              Beides ist toll & ich freu mich jedes mal, wenn ich die Fotografin bin, die euch dort mit eurer Familie fotografieren darf.
              Keine Frage. Aber wirklich verliebt habe ich mich als Familienfotografin in den <strong className={styles.strong}>Plänterwald</strong>.
              Auch hier lassen sich tolle <strong className={styles.strong}>Familienfotos am Wasser</strong> machen. Nur eben mit weniger Publikumsverkehr.
              Aber auch in <strong className={styles.strong}>Baumschulenweg</strong> gibt es tolle Spielplätze, die direkt am Wasser münden. Perfekt um die Kleinsten bei Laune zu halten ;)

              In <strong className={styles.strong}>Johannisthal</strong> freue ich mich jedes Mal über den <strong className={styles.strong}>Landschaftspark, die Königsheide und den Johannisthaler Park</strong>. Ihr seht also, Treptow hat so viel mehr zu bieten.
            </p>
          </Grid>
        </Grid>
        <Box sx={{ display: 'flex' }} className={styles.winter}>
          <div className={styles.heading}  >

            <p className={styles.largeImageLargeText}>Kinder halten uns nicht von Wichtigerem ab.</p>
            <p className={styles.largeImageLargeText}>Sie sind das Wichtigste.</p>
            <h1 className={styles.largeImageSmallText}>C.V. Levis</h1>
          </div>
        </Box>
        <Box sx={{display: 'flex'}} className={`${styles.informationText}  ${styles.informationTextResponsive}`}>
          <h3 className={`${styles.schnorkel} `}>Natürlichkeit & Nähe</h3>
          <p>
            Eine möglichst entspannte Atmosphäre liegt mir sehr am Herzen. Ein besonderer Fokus liegt bei mir darauf die echten Momente aufzufangen. Denn dieses echte Herzklopfen ist, dass was die Bilder zu Erinnerungen werden lässt.

            Ich versuche meinen Kunden möglichst wenig Anweisungen zu geben und stattdessen ihre Persönlichkeiten und Geschichten einzubringen. Ich fotografiere die Familien draußen und/oder in der von der Familie vertrauten Umgebung.

            Bei mir sollen die Kinder sich auch wie Kinder benehmen. Egal, ob sie fasziniert einen Grashalm anschauen oder voller Energie durch die Gegend springen. Mit all dieser kindlichen Begeisterung entstehen die tollsten Kinderfotos.
          </p>
        </Box>
        <Grid container  spacing={2} className={`${styles.aboutMe}  ${styles.treptow} ${styles.NoPadding}`}>
          <Grid item xs={12} md={6} className={`${styles.backgroundMoments}  ${styles.splittetBackgroundSize}`}>
          </Grid>
          <Grid item xs={12} md={6} className={styles.basicPadding}>
            <h3 className={`${styles.schnorkel}  ${styles.darkFont}`} color="black">Ihr macht den Moment &
              Ich die Fotos</h3>


            <p >

              Lasst uns gemeinsam die schönsten Foto-Erinnerungen schaffen.

              Als grünster Bezirk liefert Treptow-Köpenick die schönsten Ecken für einmalige Fotos. Mit vielen Spielplätzen, Parks, der Spree und auch kleinen Waldecken lassen sich wunderschöne Familienbilder zaubern.
            </p>
            <Link
                activeClass="active"
                to="Portfolio"
                spy={true}
                smooth={true}
                offset={-70}
                duration={500}
            >
              <Button variant="outlined">Mein Portfolio</Button>
            </Link>
          </Grid>
        </Grid>


<QuiltedImageList/>

      </div>
      <Grid container id="Kontakt">
        <Grid item xs={12} sm={4}>
          <ContactForm/>
        </Grid>
        <Grid item xs={12} sm={8} className={styles.pregnancy}>
        </Grid>
      </Grid>
    </>
  )
}
